---
- name: Configure servers with applications
  hosts: ansible1
  vars:
    servers:
      - name: web_server
        applications:
          - name: nginx
            state: present
          - name: php
            state: present
      - name: db_server
        applications:
          - name: postgresql
            state: present
          - name: redis
            state: absent
  tasks:
    - name: Show the original list of servers and applications
      debug:
        msg: "Servers: {{ servers }}"
    - name: Install and configure applications on each server
      ansible.builtin.yum:
        name: "{{ item.1.name }}"
        state: "{{ item.1.state }}"
      loop: "{{ lookup('subelements', servers, 'applications') }}"
      when: ansible_facts['distribution'] == "CentOS"
      tags: applications
    - name: Show the configuration applied
      debug:
        msg: "Server: {{ item.0.name }}, Application: {{ item.1.name }}, State: {{ item.1.state }}"
      loop: "{{ lookup('subelements', servers, 'applications') }}"
      tags: debug

